/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-surface': '#e5e2e1',
        'on-background': '#e5e2e1',
        'on-primary': '#00315e',
        'on-primary-container': '#002a53',
        'on-secondary': '#103900',
        'on-secondary-container': '#134000',
        'on-tertiary': '#442c00',
        'on-tertiary-container': '#3b2500',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        'surface': '#131313',
        'background': '#131313',
        'surface-container': '#201f1f',
        'surface-container-low': '#1c1b1b',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-high': '#2a2a2a',
        'surface-variant': '#353534',
        'outline': '#8a919f',
        'outline-variant': '#404753',
        'primary': '#a5c8ff',
        'primary-container': '#2492ff',
        'primary-fixed': '#d4e3ff',
        'secondary': '#6de039',
        'secondary-container': '#45b703',
        'secondary-fixed': '#88fd54',
        'tertiary': '#ffba45',
        'tertiary-fixed-dim': '#ffba45',
        'tertiary-container': '#c18508',
        'error': '#ffb4ab',
        'error-container': '#93000a',
        'status-active': '#52c41a',
        'status-error': '#ffb4ab',
      },
      fontFamily: {
        'data-mono': ['"JetBrains Mono"', 'monospace'],
        'address-label': ['"JetBrains Mono"', 'monospace'],
      }
    },
  },
  plugins: [],
}
