spring:
  application:
    name: modbus-tcp-java-backend
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

server:
  port: 8080
  servlet:
    context-path:

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.james.modbustcp.entity

# 日志配置
logging:
  level:
    com.james.modbustcp: INFO
    com.baomidou.mybatisplus: WARN
